---
- name: install tomcat server
  hosts: all
  become: true
  tasks:
  - name: install java
    yum:
      name: java-1.8.0-openjdk
      state: latest
  - name: download tomcat server
    get_url:
      url: http://mirror.olnevhost.net/pub/apache/tomcat/tomcat-8/v8.5.50/bin/apache-tomcat-8.5.50.tar.gz
      dest: /usr/local
  - name: extract tomcat
    unarchive:
      src: /usr/local/apache-tomcat-8.5.50.tar.gz
      dest: /usr/local
      remote_src: yes
  - name: start tomcat
    shell: /usr/local/apache-tomcat-8.5.50/bin/startup.sh                                  
                                                                          
